# Generated by Django 2.1.4 on 2019-03-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(choices=[('CNC', 'CANCEL PUNCH'), ('ADD', 'ADD PUNCH'), ('EDT', 'EDIT PUNCH')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('passphrase', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direction', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='OHClock.Employee')),
                ('Permissions', models.CharField(max_length=20)),
            ],
            bases=('OHClock.employee',),
        ),
        migrations.AddField(
            model_name='punch',
            name='EmpId',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='OHClock.Employee'),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='PunchId',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='OHClock.Punch'),
        ),
        migrations.AddField(
            model_name='adminaction',
            name='AdminId',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='OHClock.Admin'),
        ),
    ]
