# Generated by Django 2.1.4 on 2019-03-12 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OHClock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='AuthUser',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clockemp', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
