# Generated by Django 2.1.4 on 2019-03-12 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OHClock', '0005_auto_20190312_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='AuthUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockemp', to=settings.AUTH_USER_MODEL),
        ),
    ]
