# Generated by Django 2.1.4 on 2019-02-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHDock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DonationCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='Business',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='donor',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='donor',
            name='Phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
