# Generated by Django 2.1.4 on 2019-02-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OHDock', '0002_auto_20190204_0344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonationCategories',
            new_name='DonationCategory',
        ),
    ]
