# Generated by Django 2.1.4 on 2019-02-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OHDock', '0003_auto_20190214_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationcategory',
            options={'verbose_name_plural': 'Donation Categories'},
        ),
    ]
