# Generated by Django 2.1.5 on 2019-02-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHDock', '0004_auto_20190214_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='OHDock.DonationCategory')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='DonorId',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='OHDock.Donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='DumpFee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donationlines',
            name='Donation',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='OHDock.Donation'),
        ),
    ]
