# Generated by Django 2.1.4 on 2019-02-28 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('Day', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(blank=True, max_length=10)),
                ('AuthUser', models.ForeignKey(help_text="Django 'User' object used for authorization - if adding new must press + button then edit button to input first&last name", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecialHours', models.CharField(max_length=10)),
                ('EventRecurrance', models.CharField(choices=[('SN', 'Single Event'), ('FX', 'Fixed Date of Year'), ('MV', 'Moveable Date of Year')], max_length=2)),
                ('Criteria', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preference', models.CharField(choices=[('NO', "Can't Work"), ('NS', 'If Necessary'), ('YS', 'Can Work')], max_length=2, null=True)),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OHScheduler.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OHScheduler.Date')),
                ('DetailID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHScheduler.Details')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OHScheduler.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Order', models.IntegerField(null=True)),
                ('Color', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='RoleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHScheduler.Role'),
        ),
        migrations.AddField(
            model_name='details',
            name='TeamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OHScheduler.Team'),
        ),
    ]
