# Generated by Django 2.1.4 on 2019-02-28 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OHScheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='AuthUser',
            field=models.ForeignKey(help_text="Django 'User' object used for authorization - if adding new must press + button then edit button to input first&last name", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedemp', to=settings.AUTH_USER_MODEL),
        ),
    ]
