# Generated by Django 2.1.4 on 2019-02-14 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=25)),
                ('Lastname', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Business', models.CharField(blank=True, max_length=30)),
                ('OtherInfo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=25)),
                ('Lastname', models.CharField(max_length=25)),
                ('Driverstatus', models.BooleanField(help_text='Can Drive Truck')),
            ],
        ),
        migrations.CreateModel(
            name='GasStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=30)),
                ('GallonsFilled', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.TextField()),
                ('ItemLocation', models.CharField(choices=[('OUT', 'Outside location of residence (clearly marked)'), ('INF', 'Inside residence (first floor/garage)'), ('INU', 'Inside residence (upper floor)')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InputTime', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TakenDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.TextField()),
                ('DumpFee', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Triptype', models.CharField(choices=[('PD', 'Pickup/Dropoff'), ('DP', 'Dump')], max_length=2)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LicensePlate', models.CharField(max_length=20)),
                ('Capacity', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=30)),
                ('GasCapacity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='TruckAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Capacity', models.CharField(max_length=10)),
                ('AttachedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHTruck.Truck')),
            ],
        ),
        migrations.AddField(
            model_name='stop',
            name='TripId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHTruck.Trip'),
        ),
        migrations.AddField(
            model_name='gasstop',
            name='TruckFilled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHTruck.Truck'),
        ),
        migrations.AddField(
            model_name='donation',
            name='StopId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHTruck.Stop'),
        ),
    ]
