# Generated by Django 2.1.4 on 2019-02-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OHTruck', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestedDonations',
            new_name='RequestedDonation',
        ),
        migrations.RenameModel(
            old_name='TakenDonations',
            new_name='TakenDonation',
        ),
    ]
