# Generated by Django 2.1.5 on 2019-02-15 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OHTruck', '0002_auto_20190214_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='Triptype',
        ),
        migrations.AddField(
            model_name='stop',
            name='StopType',
            field=models.CharField(blank=True, choices=[('PU', 'Pickup'), ('DP', 'Dump'), ('DV', 'Delivery'), ('CU', 'House Cleanup')], max_length=2),
        ),
        migrations.AddField(
            model_name='trip',
            name='Truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHTruck.Truck'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Driverstatus',
            field=models.BooleanField(help_text='Is Authorized to Drive Truck?'),
        ),
        migrations.AddField(
            model_name='cabspot',
            name='EmpId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHTruck.Employee'),
        ),
        migrations.AddField(
            model_name='cabspot',
            name='TripId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHTruck.Trip'),
        ),
    ]
