# Generated by Django 2.1.4 on 2019-02-20 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OHTruck', '0004_truck_cabspots'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='RequesterID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OHTruck.Donor'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Address',
            field=models.CharField(help_text='Item Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Firstname',
            field=models.CharField(help_text="Donor's First Name", max_length=25),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Lastname',
            field=models.CharField(help_text="Donor's Last Name", max_length=25),
        ),
        migrations.AlterField(
            model_name='donor',
            name='OtherInfo',
            field=models.TextField(blank=True, help_text='Any other info that might be helpful'),
        ),
        migrations.AlterField(
            model_name='requesteddonation',
            name='ItemLocation',
            field=models.CharField(choices=[('OUT', 'Outside location of residence (clearly marked)'), ('INF', 'Inside residence (first floor/garage)'), ('INU', 'Inside residence (upper floor)')], help_text='Where items are located/should be delivered to', max_length=3),
        ),
        migrations.AlterField(
            model_name='truck',
            name='CabSpots',
            field=models.IntegerField(default=2, help_text='Max number of Employees who can fit in cab'),
        ),
    ]
