# Generated by Django 2.1.4 on 2019-02-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHTruck', '0006_auto_20190220_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesteddonation',
            old_name='Timestamp',
            new_name='RequestedTimestamp',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='InputTime',
            new_name='RequestedTimeframe',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='TripId',
            new_name='ScheduledTrip',
        ),
        migrations.RenameField(
            model_name='takendonation',
            old_name='Timestamp',
            new_name='ConfirmedTimestamp',
        ),
        migrations.AddField(
            model_name='stop',
            name='ScheduledOrder',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='Address',
            field=models.CharField(help_text='Where to visit', max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Firstname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Lastname',
            field=models.CharField(max_length=25),
        ),
    ]
