# Generated by Django 2.1.4 on 2019-02-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHTruck', '0007_auto_20190220_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='StatusDetail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='Status',
            field=models.CharField(choices=[('RQ', 'Requested'), ('CL', 'Called'), ('SC', 'Scheduled'), ('CM', 'Completed'), ('ER', 'Error')], max_length=2),
        ),
    ]
