# Generated by Django 2.1.4 on 2019-02-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHTruck', '0009_auto_20190220_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='RequesterID',
            new_name='RequesterId',
        ),
        migrations.AlterField(
            model_name='donor',
            name='OtherInfo',
            field=models.TextField(blank=True, help_text='Any other info that might be helpful in contacting you'),
        ),
        migrations.AlterField(
            model_name='requesteddonation',
            name='ItemLocation',
            field=models.CharField(choices=[('OUT', 'Outside location of residence (pickups clearly marked)'), ('INF', 'Inside residence (first floor/garage)'), ('INU', 'Inside residence (upper floor)')], help_text='Where items are located/should be delivered to', max_length=3),
        ),
        migrations.AlterField(
            model_name='requesteddonation',
            name='RequestedTimestamp',
            field=models.DateTimeField(help_text='When Request was Submitted', null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='RequestedTimeframe',
            field=models.DateTimeField(help_text='When would be best to complete this request'),
        ),
    ]
