# Generated by Django 2.1.4 on 2019-02-28 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OHTruck', '0010_auto_20190220_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Lastname',
        ),
        migrations.AddField(
            model_name='employee',
            name='AuthUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truckemp', to=settings.AUTH_USER_MODEL),
        ),
    ]
