# Generated by Django 2.1.4 on 2019-02-28 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OHTruck', '0012_auto_20190228_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='AuthUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='truckemp', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
