# Generated by Django 2.1.4 on 2019-03-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OHTruck', '0013_auto_20190228_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesteddonation',
            name='RequestedTimestamp',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='RequestedTimeframe',
        ),
        migrations.AddField(
            model_name='requesteddonation',
            name='RequestedTimeframe',
            field=models.DateTimeField(help_text='When would be best to complete this request', null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='RequestedTimestamp',
            field=models.DateTimeField(help_text='When Request was Submitted', null=True),
        ),
    ]
